// Generated by uRequire v0.6.19 - template: 'UMD' 
(function (window, global) {
  
var __isAMD = !!(typeof define === 'function' && define.amd),
    __isNode = (typeof exports === 'object'),
    __isWeb = !__isNode;
(function (factory) {
  if (typeof exports === 'object') {
    var nr = new (require('urequire').NodeRequirer) ('main', module, __dirname, '.');
    module.exports = factory(nr.require, exports, module, nr.require('./app'), nr.require('jquery'));
} else if (typeof define === 'function' && define.amd) { define(['require', 'exports', 'module', './app', 'jquery'], factory) } else throw new Error('uRequire: Loading UMD module as <script>, without `build.noLoaderUMD`');
}).call(this, function (require, exports, module, jsd, $) {
  

var app = new jsd.App($("body"));
  app.render();


})
}).call(this, (typeof exports === 'object' ? global : window), (typeof exports === 'object' ? global : window))