/**
 * Created by michael on 14-9-18.
 */

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
// http://json2typescript.com/

declare module J2T {

    export interface Results {
        enabled: boolean;
        interval?: number;
        groupSize: number;
    }

    export interface Jobs {
        enabled: boolean;
        interval?: number;
        groupSize: number;
    }

    export interface Files {
        enabled: boolean;
        interval?: number;
        groupSize: number;
    }

    export interface Peers {
        enabled: boolean;
        interval?: number;
        groupSize: number;
    }

    export interface Servers {
        enabled: boolean;
        interval?: number;
        groupSize: number;
    }

    export interface IceServer {
        url: string;
    }

    export interface SignalServer {
        host: string;
        isSecure: boolean;
        port: number;
    }

    export interface Broadcast {
        messageTtl: number;
        peers: Peers;
        servers: Servers;
    }

    export interface Synchronization {
        peers: Peers;
        servers: Servers;
    }

    export interface Network {
        broadcast: Broadcast;
        synchronization: Synchronization;
        useGeoLocation: boolean;
        services: any[];
    }

    export interface SettingInterface {
        authToken: string;
        maxPeers: number;
        maxFactories: number;
        maxWorkers: number;
        protocol: string;
        iceServers: IceServer[];
        signalServers: SignalServer[];
        syncInterval: number;
        uuid: string;
        network: Network;
    }

}